name: Deploy WebSite

on:
  push:
    branches:
      - main # Change to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          cd siteCv 
          yarn install

      - name: Build
        run: |
          cd siteCv 
          yarn install

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist # Change this to your build folder
          github_token: ${{ secrets.GITHUB_TOKEN }}
